version: '3.3'

services:
 server:
  restart: always
  build: ./server
  ports:
   - "3000:3000"
   - "993:993"
   - "25:25"
  env_file:
   - ./server/app/passwords.env
  volumes:
   - ./server/app:/app #use this line Linux Host
   - /var/log/TAFI:/app/logs #use this line Linux Host to mount the logs
   - /etc/localtime:/etc/localtime:ro #use this line Linux Host to use same time as the Host
  entrypoint: python app.py